#!/bin/bash

echo "*** Installing npm etc"

#https://github.com/nodesource/distributions#debinstall
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install -y nodejs

cd /vagrant
npm install --save-dev mocha
